[[chapter-2]]
== Design Patterns and Principles

=== Designing an Interface

An interface is an abstract data type, similar to a class that defines a list of `public` abstract methods that any class implementing the interface must provide.
An interface may also include constant `public static final` variables, `default` methods, and `static` methods.

[source,java]
----
public interface Fly {
    public int getWingSpan() throws Exception;
    public static final int MAX_SPEED = 100;

    public default void land() {
        System.out.println("Animal is landing");
    }
    public static double calculateSpeed(float distance, double time) {
        return distance/time;
    }
}

public class Eagle implements Fly {
    public int getWingSpan() {
        return 15;
    }
    public void land() {
        System.out.println("Eagle is diving fast");
    }
}
----

The first method of the interface, `getWingSpan()` declares an exception in the interface.
Due to the rules of method overriding, this does not require the exception to be declared in the overridden method in the Eagle class.
The second declaration, `MAX_SPEED`, is a constant `static` variable available anywhere within out application.
The next method, `land()` is a `default` method that has been optionally overridden in the Eagle class.
Finally, the method `calculateSpeed()` is `static` member and, like `MAX_SPEED`, it is available without an instance of the interface.

An interface may extend another interface, and in doing so it inherits all of the abstract methods.

[source,java]
----
public interface Walk {
    boolean isQuadruped();
    abstract double getMaxSpeed();
}

public interface Run extends Walk {
    public abstract boolean canHuntWhileRunning();
    abstract double getMaxSpeed();
}

public class Lion implements Run {
    public boolean isQuadruped() {
        return true;
    }
    public boolean canHuntWhileRunning() {
        return true;
    }
    public double getMaxSpeed() {
        return 100;
    }
}
----

The compiler automatically adds `public` to all interface methods and `abstract` to all non-static and non-default methods, if developer does not provide them.
By contrast, the class implementing the interface must provide the proper modifiers.
For example, the code would not compile if `getMaxSpeed()` was not marked `public` in the `Lion` class.
As shown in this example with `getMaxSpeed()`, interface method definitions may be duplicated in a child interface without issue.

An interface cannot extend a class, nor can class extend an interface (Lion is a class, Walk is an interface).

[source,java]
----
public interface Sleep extends Lion {} // DOES NOT COMPILE

public class Tiger extends Walk {}     // DOES NOT COMPILE
----

Interfaces also serve to provide limited support for multiple inheritance within the Java language, as a class may implement multiple interfaces, such as in the following example:

[source,java]
----
public interface Swim {}

public interface Hop {}

public class Frog implements Swim, Hop {}
----

In this example, the Frog class implements both the Swim and Hop interfaces.
An instance of Frog may be passed to any method that accepts `Swim`, `Hop`, `Frog`, or `java.lang.Object` as an input parameter.
You can also construct interfaces that have neither methods nor class members, traditionally referred to as an marker interfaces. `java.io.Serializable` is an example of a marker interface.

Interfaces cannot extend classes, nor can classes extend interfaces.
Interfaces may also not to be marked `final` or instantiated directly.
Java failing to compile if a class or interface inherits two `default` methods with the same signature and doesn't provide its own implementation.

=== Introducing Functional Programming

Java defines a _functional interface_ as an interface that contains a single abstract method.
Functional interfaces are used as the basis for lambda expressions in functional programming.
A _lambda expressions_ is a block of code that gets passed around, like an anonymous method.

==== Defining a Functional Interface

[source,java]
----
@FunctionalInterface
public interface Sprint {
    public void sprint(Animal animal);
}

public class Tiger implements Sprint {
    public void sprint(Animal animal) {
        System.out.println("Animal is sprinting fast! " + animal.toString());
    }
}
----

In this example, the Sprint is a functional interface, because it contains exactly one abstract method, and the Tiger class is valid class that implements the interface.

It is a good practice to mark a functional interface with the `@FunctionalInterface` annotation for clarity, it is not required with functional programming.
The Java compiler implicitly assumes that any interface that contains exactly one abstract method is a functional interface.
Conversely, if a class marked with `@FunctionalInterface` annotation contains more than one abstract method, or no abstract methods at all, then the compiler will detect this error and not compile.

Therefore, it is recommended that you explicitly mark the interface with the `@FunctionalInterface` annotation so that other developers know which interfaces they can safely apply lambdas to without the possibility that they may stop being functional interfaces down the road.

Which ones would also be functional interfaces?

[source,java]
----
public interface Run extends Sprint {}          // Functional Interface

public interface SpringFaster extends Sprint {  // Functional Interface
    public void sprint(Animal animal);
}

public interface Skip extends Sprint {          // Functional Interface
    public default int getHopCount(Kangaroo kangaroo) { return 10; }
    public static void skip(int speed) {}
}
----

They are valid functional interfaces.
All there are contains single abstract method.

[source,java]
----
public interface Walk {}                // NOT FUNCTIONAL INTERFACE

public interface Dance extends Sprint { // NOT FUNCTIONAL INTERFACE
    public void dance(Animal animal);
}

public interface Crawl {                // NOT FUNCTIONAL INTERFACE
    public void crawl();
    public int getCount();
}
----

The Walk, Dance and Crawl interfaces are compile but none of them are considered functional interfaces.
Applying the `@FunctionalInterface` annotation to this interfaces would result in a compiler error, as would attempting to use them implicitly as functional interfaces in a lambda expresion.

==== Implementing Functional Interfaces with Lambdas

Now that we have defined a functional interface, we'll show you how to implement them using lambda expression.

[source,java]
.Animal.java
----
public class Animal {
    private String species;
    private boolean canHop;
    private boolean canSwim;

    public Animal(String speciesName, boolean hopper, boolean swimmer) {
        species = speciesName;
        canHop = hopper;
        canSwim = swimmer;
    }

    public boolean canHop() {
        return canHop;
    }
    public boolean canSwim() {
        return canSwim;
    }
    public String toString() {
        return species;
    }
}
----

[source,java]
.CheckTrait.java
----
public interface CheckTrait {
    public boolean test(Animal a);
}
----

[source,java]
.FindMatchingAnimals.java
----
public class FindMatchingAnimals {
    private static void print(Animal animal, CheckTrait trait) {
        if(trait.test(animal))
            System.out.println(animal);
    }

    public static void main(String[] args) {
        print(new Animal("fish", false, true), a -> a.canHop());
        print(new Animal("kangaroo", true, false), a -> a.canHop());
    }
}
----

The lambda expression chosen for this program is quite simple {empty} +
`a -> a.canHop();`

We are passing this lambda as the second parameter of the `print()` method.
That method expects a `CheckTrait` as the second parameter.
Since we are passing a lambda instead, Java treats CheckTrait as a functional interface and tries to map it to the single abstract method: {empty} +
`boolean test(Animal a);`

Since this interface's method takes an Animal, it means the lambda parameter has to be an Animal.
And since that interface's method returns a boolean, we know that the lambda returns a boolean.

==== Understanding Lambda Syntax

The syntax of lambda expression is tricky because many parts are optional.
These two lines equivalent and do the exact same thing.

[source]
----
a -> a.canHop()

(Animal a) -> { return a.canHop(); }
----

The left side of the arrow operator `->` indicates the input parameters for the lambda expression.
It can be consumed by a functional interface whose abstract method has the same number of parameters and compatible data types.
The right side is referred as the body of the lambda expression.
It can be consumed by functional interface whose abstract method returns a compatible data type.

The parentheses `()` can be omitted in a lambda expression if there is exactly one input parameter and the type is not explicitly stated in the expression.
For example, the following are all valid lambda expressions, assumes that there are valid functional interfaces that can consume them:

[source,java]
----
() -> new Duck()

d -> {return d.quack;}

(Duck d) -> d.quack()

(Animal a, Duck d) -> d.quack()
----

==== Spotting Invalid Lambdas

The parenthesis can be omitted only if there is exactly one parameter and the data type is not specified.

[source,java]
----
Duck d -> d.quack()           // DOES NOT COMPILE
a,d -> d.quack()              // DOES NOT COMPILE
Animal a, Duck d -> d.quack() // DOES NOT COMPILE
----

Pair of statement braces `{}` around the body of the lambda expresion allows you to write multiple line of code in the body of the lambda expression.
When you add braces `{}`, you must explicitly terminate each statement in the body with a semicolon `;`.
And you must use the return statement if the functional interface method that lambda implements returns a value.
Alternatively, a return statement is optional when the return type of the method is `void`.
For single-line lambda bodies we were able to omit the braces `{}`, semi-colon `;` and `return` statement.

[source,java]
----
() -> true
a -> {return a.startsWith("test");}
a -> a.startsWith("test")
(int x) -> {}
(int y) -> {return;}
----

There is no rule that says the lambda expression must use them all of the input parameters.
These examples both take two parameters and ignore one of them.

[source,java]
----
(a, b) -> a.startsWith("test")
(String a, String b) -> a.startsWith("test")
----

Let's review some additional lambda expressions to see how your grasp of lambda syntax is processing.
Do you see what's wrong with each of these lambda expression.

[source,java]
----
a, b -> a.startsWith("test")         // DOES NOT COMPILE (Parenthesis required around parameter list)
c -> return 10;                      // DOES NOT COMPILE (Braces required because of return keyword)
a -> { return a.startsWith("test") } // DOES NOT COMPILE (Semicolon required after the return statement)
----

The data types for the input parameters of a lambda expression are optional.
When one parameter has a data type listed, though, all parameters must provide a data type.

[source,java]
----
(int y, z) -> {int x; return y+10;}       // DOES NOT COMPILE
(String s, z) -> { return s.length()+z; } // DOES NOT COMPILE
(a, Animal b, c) -> a.getName             // DOES NOT COMPILE
----

Java doesn't allow us to re-declare a local variable.

[source,java]
----
(a, b) -> { int a = 0; return 5; } // DOES NOT COMPILE
(a, b) -> { int c = 0; return 5; } // Compiles
----

==== Applying the Predicate Interface

[source,java]
----
public interface Predicate<T> {
    boolean test(T t);
}
----

[source,java]
.FindMatchingAnimals.java
----
import java.util.function.Predicate;

public class FindMatchingAnimals {
    private static void print(Animal animal, Predicate<Animal> trait) {
        if(trait.test(animal))
            System.out.println(animal);
    }

    public static void main(String[] args) {
        print(new Animal("fish", false, true), a -> a.canHop());
        print(new Animal("kangaroo", true, false), a -> a.canHop());
    }
}
----

=== Implementing Polymorphism

_Polymorphism_ is the ability of a single interface to support multiple underlying forms.
In Java, this allows multiple types of objects to be passed to a single method or class.

[source,java]
----
public interface LivesInOcean { public void makeSound();}

public class Dolphin implements LivesInOcean {
    public void makeSound() { System.out.println("whistle"); }
}

public class Whale implements LivesInOcean {
    public void makeSound() { System.out.println("sing"); }
}

public class Oceanographer implements LivesInOcean {
    public void checkSound(LivesInOcean animal) { animal.makeSound(); }

    public static void main() {
        Oceanographer o = new Oceanographer();
        o.checkSound(new Dolphin());
        o.checkSound(new Whale());
    }
}
----

This code compiles and executes without issue and yields the following output.

whistle {empty} +
sing

In this sample code, our `Oceanographer` class includes a method named `checkSound()` that is capable of accepting any object whose class implements `LivesInOcean` interface.

Polymorphism also allows one object to take on many different forms.
The following example illustrates this polymorphic property.

[source,java]
----
public class Primate {
    public boolean hasHair() {
        return true;
    }
}

public interface HasTail {
    public boolean isTailStriped();
}

public class Lemur extends Primate implements HasTail {
    public int age = 10;

    public boolean isTailStriped() {
        return false;
    }

    public static void main(String[] args){
      Lemur lemur = new Lemur();
      System.out.println(lemur.age);

      HasTail hasTail = lemur;
      System.out.println(hasTail.isTailStriped());

      Primate primate = lemur;
      System.out.println(primate.hasHair());
    }
}
----

This code compiles and executes without issue and yields the following output.

10 {empty} +
false {empty} +
true

The most important thing to note about this example is that only one object, `Lemur`, is created and referenced.
The ability of the `Lemur` object to be passed as an instance of an interface it implements, `HasTail`, as well as an instance of one of its superclass, `Primate`, is the nature of polymorphism.

If you use a variable to refer to an object, then only methods or variables that are part of the variable's reference type can be called without an explicit cast.

[source,java]
----
HasTail hasTail = lemur;
System.out.println(hasTail.age); // DOES NOT COMPILE

Primate primate = lemur;
System.out.println(primate.isTailStriped()); // DOES NOT COMPILE
----

==== Distinguished between an Object and a Reference

1. The type of the object determines which properties exist within the object in memory.
2. The type of references to the object determines which methods and variables are accessible to the Java program.

==== Casting Object References

Here are some basic rules to keep in mind when casting variables.

1. Casting an object from a subclass to a superclass doesn't require an explicit cast.
2. Casting an object from superclass to a subclass requires an explicit cast.
3. The compiler will not allow casts to unrelated types.
+
[source,java]
----
public class Bird {}

public class Fish {
    public static void main(String[] args){
      Fish fish = new Fish();
      Bird bird = (Bird) fish; // DOES NOT COMPILE
    }
}
----
4. Even when the code compiles without issue, an exception may be thrown at runtime if the object being cast is not actually an instance of that class.
+
[source,java]
----
public class Rodent {}

public class Capybara extends Rodent {
    public static void main(String[] args){
      Rodent rodent = new Rodent();
      Capybara capybara = (Capybara) rodent; // Throws ClassCastException at runtime
    }
}
----

=== Understanding Design Principles

A _design principle_ is an established idea or best practice that facilitates the software design process.
In general, following good design principles leads to

* More logical code,
* Code that is easier to understand
* Classes that are easier to reuse in other relationships and applications.
* Code that is easier to maintain and that adapts more readily to changes in the application requirements.

==== Encapsulating Data

In software development, _encapsulation_ is the idea of combining fields and methods in a class such that the methods operate on the data, as opposed to the users of the class accessing the fields directly.
In Java, it is commonly implemented with `private` instance members that have `public` methods to retrieve or modify the data, commonly referred to as getters and setters, respectively.

Imagine that we are designing a new `Animal` class, and we have the following design requirements:

* Each animal has a `non-null`, not empty `species` field.
* Each animal has an `age` field that is greater than or equal to zero

[source,java]
----
public class Animal {
    private String species;
    private int age;

    public Animal(String species) {
        this.setSpecies(species);
    }

    public String getSpecies() {
        return species;
    }

    public void setSpecies(String species) {
        if(species == null || species.trim().length() == 0) {
            throw new IllegalArgumentException("Species is required");
        }
        this.species = species;
    }

    public int getAge() {
        return age;
    }

    public void setAge(int age) {
        if(age < 0) {
            throw new IllegalArgumentException("Age cannot be a negative number");
        }
        this.age = age;
    }
}
----

==== Creating JavaBeans

Encapsulation is so prevalent in Java that there is a standart for creating classes that store data, called JavaBeans.
A _JavaBean_ is a design principle for encapsulating data in an object in Java.

.JavaBean naming conventions
[stripes=even,cols="3d, 4a",width="80%",options="header"]
|===
|Rule |Example

|Properties are private.
|[source,java]
----
private int age;
----

|Getters for `non-boolean` properties begins with `get`.
|[source,java]
----
private int getAge() {
  return age;
}
----

|Getters for `boolean` properties may begin `is` or `get`.
|[source,java]
----
public boolean isBird() {
  return bird;
}

public boolean getBird() {
  return bird;
}
----

|Setter methods begin with `set`.
|[source,java]
----
public void setAge(int age) {
  this.age = age;
}
----

|The method name must have a prefix of `set/get/is` followed by the first letter of the property in uppercase and followed by the rest of the property name.
|[source,java]
----
public void setNumChildren(int numChildren) {
  this.numChildren = numChildren;
}
----
|===

Although `boolean` values use `is` to start their getter method, the same does not apply to instances of the wrapper `Boolean` class, which use `get`.

==== Applying the Is-a Relationship

In object-oriented design, we describe the property of an object being an instance of a data type as having an `is-a-relationship`.
The is-a-relationship is also known as the inheritance test.

The fundamental result of the is-a principle is that if A is-a B, then any instance of A can be treated like an instance of B. This holds true for a child that is a subclass of any parent, be it a direct subclass or a distant child.

==== Applying the Has-a Relationship

In object-oriented design, we often want tı test whether an object contains a particular property or value.
We refer to the `has-a-relationship` as the property of an object having a named data object or primitive as a member.
The has-a relationship is also known as the object composition test.

==== Composing Objects

In object-oriented design, we refer to `object composition` as the property of constructing a class using references to other classes in order to reuse the functionality of the other classes.
In particular, the class contains the other classes in the has-a sense and may delegate methods to other classes.

Object composition should be thought of as an alternate to inheritance and is often used to simulate polymorphic behaviour that cannot be achieved via single inheritance.

[source,java]
----
public class Flippers {
    public void flap() {
        System.out.println("The flippers flap back and forth");
    }
}

public class WebbedFeet {
    public void kick() {
        System.out.println("The webbed feet kick to and fro");
    }
}

public class Penguin {
    private final Flippers flippers;
    private final WebbedFeet webbedFeet;

    public Penguin() {
        this.flippers = new Flippers();
        this.webbedFeet = new WebbedFeet();
    }

    public void flap() {
        this.flippers.flap();
    }

    public void kick() {
        this.webbedFeet.kick();
    }
}
----

One of the advantages of object composition over inheritance is that it tends to promote greater code reuse.
By using composition, you gain access to other classes and methods that would be difficult to obtain via Java's single-inheritance model.

=== Working with Design Patterns

A _design pattern_ is an established general solution to a commonly occurring software development problem.
The purpose of a design pattern is to leverage the wealth of knowledge of developers who have come before you in order to solve old problems that you may encounter easily.

==== Applying Singleton Pattern

*Problem* How do we create an object in memory only once in an application and have it shared by multiple classes?

*Motivation* There are times when we want only one instance of a particular type of object in memory.

*Solution* The _singleton pattern_ is a creational pattern focused on creating only one instance of an object in memory within an application, sharable by all classes and threads within the application.
The globally available object created by the singleton pattern is referred to as a _singleton_.
Singletons may also improve performance by loading reusable data that would otherwise be time consuming to store and reload each time it is needed.

[source,java]
.HayStorage.java
----
public class HayStorage {
    private int quantity = 0;
    private HayStorage() {}

    private static final HayStorage instance = new HayStorage();

    public static HayStorage getInstance() {
        return instance;
    }

    public synchronized void addHay(int amount) {
        quantity += amount;
    }

    public synchronized boolean removeHay(int amount) {
        if(quantity < amount) return false;
        quantity -= amount;
        return true;
    }

    public synchronized int getHayQuantity() {
        return quantity;
    }
}
----

Singletons in Java are created as `private static` variables within the class, often with the name `instance`.
They are accessed via a single `public static` method, often named `getInstance()`, which returns the reference to the singleton object.
Finally, all constructors in singleton class are marked `private`, which ensures that no other class is capable of instantiating another version of the class.

By marking the constructors `private`, we have implicitly marked the class `final`.
Recall that every class requires at least one constructor, with the default no-argument constructor being added if none are provided.
Furthermore, the first line of any constructor is a call to a parent constructor with the `super()` command.
If all constructors are declared `private` in the singleton class, then it is impossible to create a subclass with a valid constructor; therefore, the singleton class is effectively `final`.

NOTE: `synchronized` keyword used to prevent two processes from running the same method at the exact same time.

[source,java]
.LlamaTrainer.java
----
public class LlamaTrainer {
    public boolean feedLlamas(itn numberOfLlamas) {
        int amountNeeded = 5 * numberOfLlamas;
        HayStorage hayStorage = HayStorage.getInstance();
        if(hayStorage.getHayQuantity() < amountNeeded) {
            hayStorage.addHay(amountNeeded + 10);
        }
        boolean fed = hayStorage.removeHay(amountNeeded);
        if(fed) System.out.println("Llamas have been fed");
        return fed;
    }
}
----

In our first `HayStorage` example, we instantiated the singleton object directly in the definition of the instance reference.
We can also instantiate a singleton in two other ways.
The following example creates a singleton using a `static` initialization block when the class is loaded.

[source,java]
.StaffRegister.java
----
public class StaffRegister {
    private static final StaffRegister instance;

    static {
        instance = new StaffRegister();
        // Perform additional steps
    }

    private StaffRegister() { }

    public static StaffRegister getInstance() {
        return instance;
    }

    // Data access methods
    // ...
}
----

Both the `StaffRegister` class and our previous `HayStorage` class instantiate the singleton at the time the class is loaded.
Unlike the `HayStorage` class, though, the `StaffRegister` class instantiates the singleton as part of a `static` initialization block.
Conceptually, these two implementations are equivalent, since both create the singleton when the class is loaded, althought the `static` initialization block allows additional steps to be taken to set up the sşngleton after it has been created.
It also allows us to ahndle cases in which the `StaffRegister` constructor throws an exception.
Since the singleton is created when the class is loaded, we are able to mark the reference `final`, which guarantees only one instance will be created within our application.

Singletons are used in situations where we need access to a single set of data throughout on application.
For example, application configuration data and reusable data caches are commonly implemented using singletons.
Singletons may also be used to coordinate access to shared resources, such as coordinating write access to a file.

===== Applying Lazy Instantiation to Singletons

Another technique is to delay creation of the singleton until the first time the `getInstance` method is called:

[source,java]
.VisitorTicketTracker.java
----
public class VisitorTicketTracker {
    private static VisitorTicketTracker instance;
    private VisitorTickedTracker() {}

    public static VisitorTicketTracker getInstance() {
        if(instance == null) {
            instance = new VisitorTicketTracker(); // NOT THREAD-SAFE!
        }
        return instance;
    }

    // Data access methods
    // ...
}
----

The `VisitorTicketTracker`, does not create the singleton object when the class is loaded but rather the first time it is requested by a client.
Creating a reusable object the first time it is requested is a software design pattern known as _lazy instantiation_.
It used often in conjunction with the singleton pattern.

WARNING: When you get to writing applications that run across multiple computers, the `static` singleton solution starts to require special consideration, as each computer would have its own JVM. {empty} +
In those situations, you might still use the singleton pattern, although it might be implemented with a database or queue server rather than as a `static` object.

===== Create Unique Singletons

To truly implement the singleton pattern, we must ensure that only one instance of the singleton ever created.
Marking the constructor `private` is a good first step as it prevents the singleton from being created by other classes, but we also need to ensure that the object is only created once within the singleton class itself.
We guaranteed this in the `HayStorage` and `StaffRegister` classes by using the `final` modifier on the static reference.

Unfortunately, because we used lazy instantiation in the `VisitorTicketTracker` class,the compiler won't let us assign the `final` modifier to the `static` reference.
The implementation of `VisitorTicketTracker`, as shown, is not considered thread-safe in that two threads could call getInstance() at the same time, resulting in two objects being created.
After both threads finish executing, only one object will be set and used by other threads going forward, but the object that the two initial threads received may not be same.

_Thread safety_ is the proeprty of an object that guarantees safe execution ny multiple threads at the same time.
Simple solution that is compatible with lazy instantiation using yhe `synchronized` modifier.

[source,java]
----
public static synchronized VisitorTicketTracker getInstance() {
    if(instance == null) {
        instance = new VisitorTicketTracker(); // NOT THREAD-SAFE!
    }
    return instance;
}
----

{empty} +

The `getInstance()` method is now synchronized, which means only one thread will be allowed in the method at the time, ensuring that only one object is created.

===== Singletons with Double-Checked Locking

The `synchronized` implementation of `getInstance`, while correctly preventing multiple singleton objects from being created, has the problem that every single class call to this method will require synchronization.
In practice, this can be costly and can impact performance.
Synchronization is only needed the first time that object is created.

The solution is to use double-checked locking, a design pattern in which we first test if synchronization is needed before actually acquiring any locks.
The following is an example rewrite of this method using double-checked locking:

[source,java]
----
private static volatile VisitorTicketTracker instance;

public static VisitorTicketTracker getInstance() {
    if(instance == null) {
        synchronized(VisitorTicketTracker.class) {
            if(instance == null) {
                instance = new VisitorTicketTracker();
            }
        }
    }
    return instance;
}
----

===== Bill Pugh Singleton Implementation

A Bill Pugh Singleton uses inner classes and does not use any synchronization construct.
It uses static blocks, but in a different way — and suggests using static inner classes.

[source,java]
----
public class BillPughSingleton {
    private BillPughSingleton(){}

    private static class SingletonHelper {
        private static final BillPughSingleton INSTANCE = new BillPughSingleton();
    }

    public static BillPughSingleton getInstance(){
        return SingletonHelper.INSTANCE;
    }
}
----

Notice the private inner static class that contains the instance of the singleton class.
When the singleton class is loaded, `SingletonHelper` class is not loaded into memory and only when someone calls the getInstance method, this class gets loaded and creates the Singleton class instance.

IMPORTANT: Reflection can be used to destroy all the above singleton implementation approaches

===== Enum Singleton

To overcome this situation with Reflection, Joshua Bloch suggests the use of Enum to implement Singleton design pattern as Java ensures that any enum value is instantiated only once in a Java program.
The drawback is that the enum type is somewhat inflexible; for example, it does not allow lazy initialization.

[source,java]
----
public enum EnumSingleton {
    INSTANCE
}
----

==== Create Immutable Objects

*Problem* How do we create read-only objects that can be shared and used by multiple classes?

*Motivation* Sometimes we want to create simple objects that can be shared across multiple classes, but for security reasons we don't want their value to be modified.
We could copy the object before sending it to another method, bu this creates a large overhead that duplicates the object every time it is passed.
Furthermore, if we have multiple threads accessing the same object, we could run into concurrency issues.

*Solution* _The immutable object pattern_ is a creational pattern based on the idea of creating object whose state does not change after they are created and can be easily shared multiple classes.
Immutable objects go hand and hand with encapsulation, except that no setter methods exist that modify the object.
Since the state of an immutable object never changes, they are inherently thread-safe.

===== Applying an Immutable Strategy

1. Use a constructor to set all properties of object.
2. Mark all of the instance variables `private` and `final`.
3. Don't define any setter methods.
4. Don't allow referenced mutable objects to be modified or accessed directly.
5. Prevent methods from being overridden.

The fourth rule requires a little more explanation.
Let's say that you have immutable `Animal` object, which contains a reference to a `List` of the animal's favorite foods, as shown in the following example.

[source,java]
.Animal.java
----
import java.util.ArrayList;

public final class Animal {
    private final List<String> favoriteFoods;

    public Animal(List<String> favoriteFoods) {
        if(favoriteFoods == null) {
            throw new RuntimeException("favoriteFoods is required");
        }
        this.favoriteFoods = new ArrayList<String>(favoriteFoods);
    }

    public List<String> getFavoriteFoods() { // MAKE CLASS MUTABLE!
        return favoriteFoods;
    }
}
----

==== Using the Builder Pattern

==== Creating Objects with the Factory Pattern

